sudo: required
services:
  - docker

before_install:
  - docker build -t sangmin/docker-react -f Dockerfile.dev .

script:
  - docker run sangmin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-test1"
  env: "DockerTest1-env"
  bucket_name: "elasticbeanstalk-us-east-1-398215493199"
  bucket_path: "docker-test1"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KET



